// @ts-nocheck
import { textToSpeech, speechToText, voiceSpeaker, voiceEncoding, voiceContentType } from "./voice";
import { withSecurityHeaders, clientIp, rateLimit, isAdminRequest, adminCookie, clearAdminCookie } from "./security";
import { isMedicalQuery, detectMedicalSpecialties, recommendMedicalProviders } from "./medical-directory";
import { getMedicalInternalContext } from "./medical-internal-knowledge";
import { bedrockChat, bedrockConfigured, bedrockModel } from "./bedrock";

const BRAND="Nexa AI";
const POWERED_BY="SPRINGNEXA PRIVATE LIMITED (IT Division)";
const COMPANY="SpringNexa Private Limited";
const FAST_MODEL="@cf/zai-org/glm-4.7-flash";
const MEDICAL_DEFAULT="google/medgemma-27b-it";
const TIMEOUT_MS=8000;
const DEFAULT_SYSTEM=`You are Nexa AI, powered by ${POWERED_BY}. Be accurate, useful and concise. Never claim to be a doctor. Do not invent hospitals, doctors, credentials, statistics or citations.`;
const MEDICAL_SYSTEM=`You are Nexa AI Medical, powered by ${POWERED_BY}. Provide medical education and decision support, not a definitive diagnosis or prescription. Distinguish possibilities from diagnosis. For emergencies advise immediate local medical care. Do not invent clinicians, hospitals or medical records. Use supplied NEXA evidence and structured EDX knowledge when present. Preserve uncertainty and clinician-review requirements.`;

type Message={role:"system"|"user"|"assistant";content:string};
type Result={content:string;provider:string;model:string};

function json(data:any,status=200,extra?:HeadersInit){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...extra}})}
function cors(r:Response){const h=new Headers(r.headers);h.set("access-control-allow-origin","*");h.set("access-control-allow-methods","GET,POST,OPTIONS");h.set("access-control-allow-headers","content-type,authorization,cookie,x-admin-token");return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})}
function messages(body:any):Message[]{return (Array.isArray(body?.messages)?body.messages:[]).filter((m:any)=>m&&["system","user","assistant"].includes(m.role)&&typeof m.content==="string").slice(-12)}
function timeoutFetch(url:string,init:RequestInit){return fetch(url,{...init,signal:AbortSignal.timeout(TIMEOUT_MS)})}
async function openAI(key:string,url:string,model:string,msgs:Message[],provider:string):Promise<Result>{const r=await timeoutFetch(url,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${key}`},body:JSON.stringify({model,messages:msgs,temperature:.15,max_tokens:1200,stream:false})});if(!r.ok)throw new Error(`${provider}:${r.status}`);const d:any=await r.json();const c=d?.choices?.[0]?.message?.content;if(typeof c!=="string"||!c.trim())throw new Error(`${provider}:invalid_response`);return{content:c,provider,model}}
async function cloudflare(env:any,msgs:Message[],model:string):Promise<Result>{if(!env.AI)throw new Error("cloudflare:AI_binding_unavailable");const d:any=await env.AI.run(model,{messages:msgs,max_tokens:1200,temperature:.15});const c=d?.response??d?.choices?.[0]?.message?.content;if(typeof c!=="string"||!c.trim())throw new Error("cloudflare:invalid_response");return{content:c,provider:"cloudflare",model}}
async function google(env:any,msgs:Message[],model:string):Promise<Result>{if(!env.GOOGLE_API_KEY)throw new Error("google:not_configured");const system=msgs.find(m=>m.role==="system")?.content;const contents=msgs.filter(m=>m.role!=="system").map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]}));const r=await timeoutFetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(env.GOOGLE_API_KEY)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...(system?{systemInstruction:{parts:[{text:system}]}}:{}),contents,generationConfig:{temperature:.15,maxOutputTokens:1200}})});if(!r.ok)throw new Error(`google:${r.status}`);const d:any=await r.json();const c=d?.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||"").join("");if(!c)throw new Error("google:invalid_response");return{content:c,provider:"google",model}}
async function vision(env:any,prompt:string,image:any):Promise<Result>{if(!env.GOOGLE_API_KEY)throw new Error("vision:not_configured");const model=env.GOOGLE_MODEL||"gemini-2.5-flash";const r=await timeoutFetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(env.GOOGLE_API_KEY)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contents:[{role:"user",parts:[{text:`${DEFAULT_SYSTEM}\n\n${prompt}`},{inline_data:{mime_type:image.mimeType,data:image.data}}]}],generationConfig:{temperature:.2,maxOutputTokens:1200}})});if(!r.ok)throw new Error(`vision:${r.status}`);const d:any=await r.json();const c=d?.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||"").join("");if(!c)throw new Error("vision:invalid_response");return{content:c,provider:"google",model}}
async function medical(env:any,msgs:Message[],model:string):Promise<Result>{const preferred=model?.startsWith("@cf/")?model:FAST_MODEL;try{return await cloudflare(env,msgs,preferred)}catch(e){if(!env.HF_TOKEN)throw e;return openAI(env.HF_TOKEN,"https://router.huggingface.co/v1/chat/completions",model||env.MEDICAL_MODEL||MEDICAL_DEFAULT,msgs,"medical")}}
async function answer(env:any,msgs:Message[],provider="auto",requestedModel?:string):Promise<Result>{const selected=provider.toLowerCase();const errors:string[]=[];if(selected==="medical"){try{return await medical(env,msgs,requestedModel||env.MEDICAL_MODEL||MEDICAL_DEFAULT)}catch(e){errors.push(e instanceof Error?e.message:"medical:error");throw new Error(errors.join(","))}}
const order=selected==="auto"?["cloudflare","groq","google","nvidia"]:[selected];
for(const p of order){try{if(p==="cloudflare")return await cloudflare(env,msgs,requestedModel?.startsWith("@cf/")?requestedModel:FAST_MODEL);if(p==="groq"&&env.GROQ_API_KEY)return await openAI(env.GROQ_API_KEY,"https://api.groq.com/openai/v1/chat/completions",env.GROQ_MODEL||"openai/gpt-oss-20b",msgs,"groq");if(p==="google"&&env.GOOGLE_API_KEY)return await google(env,msgs,requestedModel||env.GOOGLE_MODEL||"gemini-2.5-flash");if(p==="nvidia"&&env.NVIDIA_API_KEY)return await openAI(env.NVIDIA_API_KEY,"https://integrate.api.nvidia.com/v1/chat/completions",env.NVIDIA_MODEL||"openai/gpt-oss-120b",msgs,"nvidia");if(p==="bedrock")return await bedrockChat(env,msgs)}catch(e){errors.push(e instanceof Error?e.message:`${p}:error`)}}
throw new Error(errors.join(",")||"no_provider_available")}

export default {async fetch(request:Request,env:any):Promise<Response>{const url=new URL(request.url);if(request.method==="OPTIONS")return cors(new Response(null,{status:204}));if(url.pathname==="/health"&&request.method==="GET")return cors(json({ok:true,service:BRAND,poweredBy:POWERED_BY,company:COMPANY,division:"IT Division",modes:["auto","medical","voice"]}));
if(url.pathname==="/v1/models"&&request.method==="GET")return cors(json({brand:BRAND,poweredBy:POWERED_BY,company:COMPANY,models:[{id:"auto",name:"Nexa AI Auto",type:"general"},{id:"medical",name:"Nexa AI Medical",type:"medical"},{id:"voice",name:"Nexa Voice",type:"voice"},{id:"bedrock",name:"Nexa Bedrock",type:"general",configured:bedrockConfigured(env),model:bedrockConfigured(env)?bedrockModel(env):null}]}));
if(url.pathname==="/v1/medical/specialties"&&request.method==="GET")return cors(json({specialties:detectMedicalSpecialties(url.searchParams.get("q")||""),directory:"verified-only"}));
if(url.pathname==="/v1/medical/providers"&&request.method==="GET")return cors(json(recommendMedicalProviders(url.searchParams.get("q")||"",url.searchParams.get("location")||"",(url.searchParams.get("type") as any)||undefined)));
if(url.pathname==="/v1/voice/capabilities"&&request.method==="GET")return cors(json({brand:BRAND,product:"Nexa Voice",speechToText:true,textToSpeech:true,providers:{elevenlabs:!!env.ELEVENLABS_API_KEY,cloudflare:true},languages:["en","hi","ur","doi","ks","goj"],formats:["mp3","opus","wav"]}));
if(url.pathname==="/v1/audio/speech"&&request.method==="POST"){try{const b:any=await request.json();const text=typeof b?.input==="string"?b.input:typeof b?.text==="string"?b.text:"";if(!text.trim())return cors(json({error:"input is required"},400));const enc=voiceEncoding(b?.response_format||b?.format);const a=await textToSpeech(env,text,voiceSpeaker(b?.voice),enc);return cors(new Response(a.body,{status:a.status,headers:{"content-type":voiceContentType(enc),"cache-control":"no-store","x-nexa-product":"Nexa Voice"}}))}catch{return cors(json({error:"Voice generation failed"},503))}}
if(url.pathname==="/v1/audio/transcriptions"&&request.method==="POST"){try{const ct=request.headers.get("content-type")||"";let audio:ArrayBuffer,language:string|undefined;if(ct.includes("multipart/form-data")){const f=await request.formData(),file=f.get("file");if(!(file instanceof File))return cors(json({error:"audio file is required"},400));audio=await file.arrayBuffer();language=typeof f.get("language")==="string"?String(f.get("language")):undefined}else{audio=await request.arrayBuffer();language=url.searchParams.get("language")||undefined}const r=await speechToText(env,audio,language);return cors(json({brand:BRAND,product:"Nexa Voice",text:r.text,wordCount:r.wordCount,vtt:r.vtt}))}catch{return cors(json({error:"Voice transcription failed"},503))}}
if(url.pathname==="/v1/vision"&&request.method==="POST"){try{const b:any=await request.json();const image=b?.image||b?.input_image;if(!image?.data)return cors(json({error:"image data is required"},400));const r=await vision(env,String(b?.prompt||"Analyze this medical image carefully."),{mimeType:String(image.mimeType||image.mime_type||"image/jpeg"),data:String(image.data)});return cors(json({id:crypto.randomUUID(),object:"vision.completion",brand:BRAND,provider:r.provider,model:r.model,choices:[{index:0,message:{role:"assistant",content:r.content},finish_reason:"stop"}]}))}catch(e){return cors(json({error:"Vision service temporarily unavailable",detail:e instanceof Error?e.message:"vision_error"},503))}}
if(url.pathname==="/v1/chat/completions"&&request.method==="POST"){try{const b:any=await request.json();const msgs=messages(b);if(!msgs.some(m=>m.role==="user"))return cors(json({error:"messages with a user message are required"},400));const selected=typeof b.provider==="string"?b.provider:typeof b.mode==="string"?b.mode:"auto";if(!msgs.some(m=>m.role==="system")){const q=[...msgs].reverse().find(m=>m.role==="user")?.content||"";const medicalMode=selected.toLowerCase()==="medical"||isMedicalQuery(q);msgs.unshift({role:"system",content:medicalMode?`${MEDICAL_SYSTEM}\n\n${getMedicalInternalContext(q)}`:DEFAULT_SYSTEM})}const r=await answer(env,msgs,selected,typeof b.model==="string"?b.model:undefined);return cors(json({id:crypto.randomUUID(),object:"chat.completion",created:Math.floor(Date.now()/1000),brand:BRAND,poweredBy:POWERED_BY,company:COMPANY,provider:r.provider,model:r.model,choices:[{index:0,message:{role:"assistant",content:r.content},finish_reason:"stop"}]}))}catch(e){return cors(json({error:"AI service temporarily unavailable",detail:e instanceof Error?e.message:"provider_error"},503))}}
if(url.pathname==="/v1/admin/status"&&request.method==="GET"){if(!isAdminRequest(request,env.ADMIN_TOKEN))return cors(json({error:"Unauthorized"},401));return cors(json({ok:true,admin:true,service:BRAND,secretsConfigured:{groq:!!env.GROQ_API_KEY,google:!!env.GOOGLE_API_KEY,nvidia:!!env.NVIDIA_API_KEY,medical:!!env.HF_TOKEN,elevenlabs:!!env.ELEVENLABS_API_KEY,admin:!!env.ADMIN_TOKEN}}))}
if(url.pathname==="/v1/admin/logout"&&request.method==="POST"){return cors(clearAdminCookie())}
const asset=await env.ASSETS.fetch(request);return withSecurityHeaders(asset)}};
