export const MEDICAL_BOOK_KNOWLEDGE_VERSION = "preston-shapiro-4e-1.1.0";

// Structured reference layer derived from the user-supplied Preston/Shapiro 4th edition.
// The public repository intentionally stores summaries and retrieval rules, not the copyrighted book text.
const TOPICS = [
  { keys:["carpal tunnel","cts","median neuropathy","median nerve"], text:"Book-derived context: localize median neuropathy at the wrist using clinical symptoms/examination plus sensory and motor NCS and appropriate comparative/segmental techniques. Sensory abnormalities are often prominent. Distinguish clinically meaningful CTS from incidental median slowing in generalized polyneuropathy or another localization." },
  { keys:["ulnar","guyon","elbow neuropathy"], text:"Book-derived context: ulnar neuropathy requires segmental localization, technically adequate stimulation and recording, comparison with other nerves when useful, and targeted needle EMG of muscles supplied by different ulnar branches. Do not assume a common entrapment site explains every abnormality." },
  { keys:["radiculopathy","root","paraspinal","dorsal root ganglion","drg"], text:"Book-derived context: radiculopathy is a localization problem requiring clinical correlation. Sensory responses can remain normal with lesions proximal to the dorsal root ganglion. Needle EMG distribution, including paraspinal sampling when appropriate, contributes to localization; isolated abnormalities are not sufficient by themselves." },
  { keys:["demyelinating","demyelination","conduction block","temporal dispersion","cidp","cmt1"], text:"Book-derived context: assess demyelinating physiology from the combined pattern of conduction slowing, prolonged distal latencies, late-response abnormalities and conduction block/temporal dispersion. Check technical adequacy and common entrapment segments first. CMAP amplitude loss alone is not proof of demyelination. Reference criteria are laboratory- and disorder-dependent." },
  { keys:["axonal","axonopathy","denervation","reinnervation","fibrillation","positive sharp"], text:"Book-derived context: axonal loss commonly reduces CMAP and/or SNAP amplitudes. Needle EMG may show active denervation; chronic lesions may show reinnervation with larger/longer-duration and more complex MUAPs plus reduced recruitment. In acute axonal loss, recruitment abnormalities can precede mature MUAP remodeling, so symptom timing matters." },
  { keys:["ncs","nerve conduction","nerve conduction study","cmaps","smap","snap","latency","conduction velocity","amplitude"], text:"Book-derived context: motor NCS evaluates CMAP latency, amplitude, area, duration and segmental conduction velocity; distal latency includes distal nerve, NMJ and muscle components, so two stimulation sites are needed for true segmental motor velocity. Sensory NCS evaluates SNAP latency, amplitude, duration and velocity; onset latency represents the fastest fibers and can be used for velocity calculation. Interpret actual reported values against the laboratory's reference ranges and technical conditions." },
  { keys:["f wave","f-wave","f waves","h reflex","h-reflex","late response"], text:"Book-derived context: F waves and H reflexes complement routine NCS by sampling proximal motor/reflex pathways. Interpret latency and persistence with the nerve tested, CMAP size, stimulation quality and clinical context; absent late responses are not automatically abnormal when the distal CMAP is severely reduced." },
  { keys:["needle emg","emg","muap","motor unit","recruitment","fasciculation","myotonic"], text:"Book-derived context: needle EMG interpretation integrates insertional activity, spontaneous activity, MUAP morphology and activation/recruitment. Fibrillation potentials and positive sharp waves support active denervation; fasciculations and myotonic discharges have distinct meanings and require distribution and clinical correlation." },
  { keys:["myopathy","muscle disease","myopathic"], text:"Book-derived context: in many myopathies sensory NCS remains normal unless a coexisting neuropathy exists. Motor responses may be normal or reduced in severe/distal-predominant disease. Needle EMG is interpreted from MUAP morphology, recruitment and spontaneous activity together with the clinical pattern." },
  { keys:["myasthenia","neuromuscular junction","nmj","repetitive nerve stimulation","rns","lambert","lems"], text:"Book-derived context: suspected NMJ disease may require repetitive nerve stimulation and/or exercise testing in addition to routine NCS and needle EMG. Postsynaptic and presynaptic disorders produce different response patterns. Protocol choice, muscle selection, baseline CMAP, temperature, medications and clinical phenotype affect interpretation." },
  { keys:["als","motor neuron","motor neuron disease"], text:"Book-derived context: motor neuron disorders may show widespread active and chronic denervation with reduced recruitment while sensory studies may remain relatively preserved. Interpret across multiple regions and integrate upper- and lower-motor-neuron clinical findings. Apparent slowing associated with low CMAP amplitudes should not automatically be called demyelination." },
  { keys:["polyneuropathy","neuropathy","length dependent","sensorimotor"], text:"Book-derived context: polyneuropathy interpretation considers symmetry, distribution, sensory versus motor predominance, axonal versus demyelinating features and clinical time course. Incidental slowing at common entrapment sites can coexist with generalized neuropathy and does not automatically establish symptomatic focal entrapment." },
  { keys:["pediatric","child","infant","icu","critical illness","ventilator"], text:"Book-derived context: pediatric and ICU EDX requires setting-specific interpretation because maturation, age, temperature, edema, medications, cooperation and critical illness can alter findings. Study selection and reference values must match the clinical population." },
  { keys:["ultrasound","neuromuscular ultrasound","nerve csa","cross sectional area"], text:"Book-derived context: neuromuscular ultrasound provides structural and dynamic information about nerves, muscles and surrounding tissues and complements EDX physiology. It does not replace EDX. Findings should be interpreted with history, examination and electrophysiologic results." },
  { keys:["artifact","temperature","technical","electrode","stimulation","reference range","quality"], text:"Book-derived context: technical quality is part of interpretation. Check limb temperature, electrode placement, stimulation adequacy and location, distance measurement, artifacts, co-stimulation, waveform morphology and laboratory-specific reference ranges before labeling an abnormality." }
];

const BASE = "Use the supplied Preston/Shapiro 4th-edition material as a reference layer for neurophysiology, NCS, EMG, EEG/EDX and related educational questions. The repository stores structured summaries rather than the copyrighted book text. Nexa may answer neurophysiology questions and analyze user-provided NCS/EMG/EDX report values. Do not give a blanket refusal merely because the question concerns a specific study. For patient-specific reports, clearly separate observed values, technical limitations and educational interpretation, and recommend qualified clinician review.";

export function getMedicalBookContext(query:string): string {
  const q = String(query || "").toLowerCase().replace(/[–—]/g, "-");
  const matched = TOPICS.filter(t => t.keys.some(k => q.includes(k))).slice(0,6).map(t => t.text);
  const ncsIntent = /\b(ncs|ncv|ncs\/ncv|nerve conduction|nerve conduction study|snap|smap|cmaps?|conduction velocity|distal latency|f-?wave|h-?reflex)\b/i.test(q);
  const emgIntent = /\b(emg|needle|muap|recruitment|denervation|fibrillation|positive sharp)\b/i.test(q);
  if (ncsIntent && !matched.some(x => x.includes("motor NCS evaluates"))) matched.unshift(TOPICS.find(t => t.keys.includes("ncs"))!.text);
  if (emgIntent && !matched.some(x => x.includes("needle EMG interpretation"))) matched.push(TOPICS.find(t => t.keys.includes("needle emg"))!.text);
  return matched.length ? `${BASE}\n\nRelevant book-derived topics:\n- ${matched.slice(0,6).join("\n- ")}` : BASE;
}
