import { DurableObject } from "cloudflare:workers";

export type LiveSource = { id:string; name:string; url:string; authority:string; refreshHours?:number; ingestion?:string };
export type EvidenceHit = { chunkId:string; sourceId:string; title:string; authority:string; url:string; text:string; score:number; version:string; retrievedAt:string };
export type MedicalAudit = { id:string; createdAt:string; requestHash:string; queryHash:string; userHash?:string; sourceIds:string[]; chunkIds:string[]; sourceVersions:string[]; retrievalTimestamp?:string; model:string; provider:string; answerHash:string; generatedConclusion:string; uncertainty:string; humanReviewStatus:"required"|"pending"|"reviewed"|"not-required"; safety:string[]; prevAuditHash?:string; recordHash?:string };

const EMBEDDING_MODEL="@cf/baai/bge-base-en-v1.5";
const MAX_TEXT=180000, CHUNK=1200, OVERLAP=180;
function cleanText(input:string):string{return input.replace(/<script[\\s\\S]*?<\\/script>/gi," ").replace(/<style[\\s\\S]*?<\\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/\\s+/g," ").trim().slice(0,MAX_TEXT)}
export async function sha256(value:string):Promise<string>{const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function chunks(text:string):string[]{const out:string[]=[];for(let i=0;i<text.length;i+=CHUNK-OVERLAP)out.push(text.slice(i,i+CHUNK).trim());return out.filter(x=>x.length>80)}
function cosine(a:number[],b:number[]):number{let dot=0,aa=0,bb=0;const n=Math.min(a.length,b.length);for(let i=0;i<n;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i]}return aa&&bb?dot/Math.sqrt(aa*bb):0}
function explainAnswer(answer:string):{conclusion:string;uncertainty:string}{const normalized=answer.replace(/\\s+/g," ").trim();const uncertaintySentences=normalized.split(/(?<=[.!?])\\s+/).filter(s=>/\\b(uncertain|uncertainty|cannot|can't|may|might|possible|possibly|suggests|suggest|limitations?|insufficient|not enough|clinician|review)\\b/i.test(s));const conclusionMatch=normalized.match(/(?:conclusion|impression|assessment|overall)\\s*[:\\-]\\s*([^\\n]{1,1000})/i);return{conclusion:(conclusionMatch?.[1]||normalized.slice(0,1000)).slice(0,1000),uncertainty:(uncertaintySentences.slice(0,5).join(" ")||"Uncertainty must be assessed by a qualified clinician; the model output is decision support, not a definitive diagnosis.").slice(0,1500)}}

export class MedicalEvidenceDO extends DurableObject{
  constructor(ctx:DurableObjectState,env:Env){super(ctx,env);ctx.storage.sql.exec(`
    CREATE TABLE IF NOT EXISTS sources(id TEXT PRIMARY KEY,name TEXT NOT NULL,url TEXT NOT NULL,authority TEXT NOT NULL,last_checked TEXT,last_changed TEXT,content_hash TEXT,version TEXT,stale INTEGER DEFAULT 0,http_status INTEGER);
    CREATE TABLE IF NOT EXISTS chunks(id TEXT PRIMARY KEY,source_id TEXT NOT NULL,text TEXT NOT NULL,embedding TEXT NOT NULL,version TEXT NOT NULL,created_at TEXT NOT NULL);
    CREATE INDEX IF NOT EXISTS idx_chunks_source ON chunks(source_id);
    CREATE TABLE IF NOT EXISTS audits(seq INTEGER PRIMARY KEY,id TEXT UNIQUE NOT NULL,created_at TEXT NOT NULL,request_hash TEXT,query_hash TEXT,user_hash TEXT,source_ids TEXT,chunk_ids TEXT,source_versions TEXT,retrieval_timestamp TEXT,model TEXT,provider TEXT,answer_hash TEXT,generated_conclusion TEXT,uncertainty TEXT,human_review_status TEXT,safety TEXT,prev_audit_hash TEXT,record_hash TEXT);
    CREATE INDEX IF NOT EXISTS idx_audits_created ON audits(created_at);
    CREATE INDEX IF NOT EXISTS idx_audits_hash ON audits(record_hash);
  `);try{ctx.storage.sql.exec("ALTER TABLE audits ADD COLUMN seq INTEGER")}catch{}try{ctx.storage.sql.exec("ALTER TABLE audits ADD COLUMN retrieval_timestamp TEXT")}catch{}try{ctx.storage.sql.exec("ALTER TABLE audits ADD COLUMN generated_conclusion TEXT")}catch{}try{ctx.storage.sql.exec("ALTER TABLE audits ADD COLUMN uncertainty TEXT")}catch{}try{ctx.storage.sql.exec("ALTER TABLE audits ADD COLUMN human_review_status TEXT")}catch{}try{ctx.storage.sql.exec("ALTER TABLE audits ADD COLUMN prev_audit_hash TEXT")}catch{}try{ctx.storage.sql.exec("ALTER TABLE audits ADD COLUMN record_hash TEXT")}catch{}
    try{ctx.storage.sql.exec("UPDATE audits SET seq=rowid WHERE seq IS NULL")}catch{}
  }
  async upsertSource(source:LiveSource,text:string,contentHash:string,version:string,embeddings:number[][],status:number):Promise<{changed:boolean;version:string;chunks:number}>{const now=new Date().toISOString();const old=this.ctx.storage.sql.exec("SELECT content_hash,version FROM sources WHERE id=?",source.id).toArray()[0] as any;const changed=!old||old.content_hash!==contentHash;this.ctx.storage.sql.exec("INSERT INTO sources(id,name,url,authority,last_checked,last_changed,content_hash,version,stale,http_status) VALUES(?,?,?,?,?,?,?,?,0,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,url=excluded.url,authority=excluded.authority,last_checked=excluded.last_checked,last_changed=CASE WHEN excluded.content_hash!=sources.content_hash THEN excluded.last_checked ELSE sources.last_changed END,content_hash=excluded.content_hash,version=excluded.version,stale=0,http_status=excluded.http_status",source.id,source.name,source.url,source.authority,now,now,contentHash,version,status);if(changed){const cs=chunks(text);this.ctx.storage.sql.exec("DELETE FROM chunks WHERE source_id=?",source.id);for(let i=0;i<cs.length;i++)this.ctx.storage.sql.exec("INSERT INTO chunks(id,source_id,text,embedding,version,created_at) VALUES(?,?,?,?,?,?)",`${source.id}:${version}:${i}`,source.id,cs[i],JSON.stringify(embeddings[i]||[]),version,now)}return{changed,version,chunks:changed?chunks(text).length:Number(this.ctx.storage.sql.exec("SELECT count(*) c FROM chunks WHERE source_id=?",source.id).toArray()[0]?.c||0)}}
  async search(queryVector:number[],limit=8):Promise<EvidenceHit[]>{const rows=this.ctx.storage.sql.exec("SELECT c.id,c.source_id,c.text,c.embedding,c.version,s.name,s.authority,s.url,s.stale FROM chunks c JOIN sources s ON s.id=c.source_id WHERE s.stale=0").toArray() as any[];const now=new Date().toISOString();return rows.map(r=>({chunkId:String(r.id),sourceId:String(r.source_id),title:String(r.name),authority:String(r.authority),url:String(r.url),text:String(r.text),score:cosine(queryVector,JSON.parse(String(r.embedding))),version:String(r.version),retrievedAt:now})).sort((a,b)=>b.score-a.score).slice(0,limit)}
  async markStale(maxAgeHours=720):Promise<string[]>{const cutoff=Date.now()-maxAgeHours*3600000;const rows=this.ctx.storage.sql.exec("SELECT id,last_checked FROM sources").toArray() as any[];const stale:string[]=[];for(const r of rows){if(!r.last_checked||Date.parse(String(r.last_checked))<cutoff){this.ctx.storage.sql.exec("UPDATE sources SET stale=1 WHERE id=?",r.id);stale.push(String(r.id))}}return stale}
  async listSources(){return this.ctx.storage.sql.exec("SELECT id,name,url,authority,last_checked,last_changed,version,content_hash,stale,http_status FROM sources ORDER BY name").toArray()}
  async audit(a:MedicalAudit){const latest=this.ctx.storage.sql.exec("SELECT seq,record_hash FROM audits ORDER BY seq DESC LIMIT 1").toArray()[0] as any;const seq=Number(latest?.seq||0)+1;const prevAuditHash=String(a.prevAuditHash||latest?.record_hash||"");const payload={seq,id:a.id,createdAt:a.createdAt,requestHash:a.requestHash,queryHash:a.queryHash,userHash:a.userHash||"",sourceIds:a.sourceIds,chunkIds:a.chunkIds,sourceVersions:a.sourceVersions,retrievalTimestamp:a.retrievalTimestamp||a.createdAt,model:a.model,provider:a.provider,answerHash:a.answerHash,generatedConclusion:a.generatedConclusion,uncertainty:a.uncertainty,humanReviewStatus:a.humanReviewStatus,safety:a.safety,prevAuditHash};const recordHash=await sha256(JSON.stringify(payload));this.ctx.storage.sql.exec("INSERT INTO audits(seq,id,created_at,request_hash,query_hash,user_hash,source_ids,chunk_ids,source_versions,retrieval_timestamp,model,provider,answer_hash,generated_conclusion,uncertainty,human_review_status,safety,prev_audit_hash,record_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",seq,a.id,a.createdAt,a.requestHash,a.queryHash,a.userHash||"",JSON.stringify(a.sourceIds),JSON.stringify(a.chunkIds),JSON.stringify(a.sourceVersions),a.retrievalTimestamp||a.createdAt,a.model,a.provider,a.answerHash,a.generatedConclusion,a.uncertainty,a.humanReviewStatus,JSON.stringify(a.safety),prevAuditHash,recordHash);return{id:a.id,seq,recordHash,prevAuditHash}}
  async audits(limit=50){return this.ctx.storage.sql.exec("SELECT * FROM audits ORDER BY seq DESC LIMIT ?",Math.min(Math.max(limit,1),200)).toArray()}
  async verifyAuditChain():Promise<{valid:boolean;checked:number;brokenAt?:string}>{const rows=this.ctx.storage.sql.exec("SELECT * FROM audits ORDER BY seq ASC").toArray() as any[];let previous="",expectedSeq=1;for(const r of rows){const payload={seq:Number(r.seq),id:r.id,createdAt:r.created_at,requestHash:r.request_hash,queryHash:r.query_hash,userHash:r.user_hash||"",sourceIds:JSON.parse(r.source_ids||"[]"),chunkIds:JSON.parse(r.chunk_ids||"[]"),sourceVersions:JSON.parse(r.source_versions||"[]"),retrievalTimestamp:r.retrieval_timestamp||r.created_at,model:r.model,provider:r.provider,answerHash:r.answer_hash,generatedConclusion:r.generated_conclusion||"",uncertainty:r.uncertainty||"",humanReviewStatus:r.human_review_status||"required",safety:JSON.parse(r.safety||"[]"),prevAuditHash:r.prev_audit_hash||""};const expected=await sha256(JSON.stringify(payload));if(Number(r.seq)!==expectedSeq||(r.prev_audit_hash||"")!==previous||r.record_hash!==expected)return{valid:false,checked:expectedSeq,brokenAt:String(r.id)};previous=String(r.record_hash);expectedSeq++}return{valid:true,checked:rows.length}}
}

export type Env={AI:Ai;MEDICAL_EVIDENCE:DurableObjectNamespace<MedicalEvidenceDO>;[key:string]:any};
async function embed(env:Env,texts:string[]):Promise<number[][]>{const result:any=await env.AI.run(EMBEDDING_MODEL,{text:texts});return(result?.data||result?.embeddings||[]).map((x:any)=>Array.isArray(x)?x:(x?.embedding||[]))}
export async function queryLiveEvidence(env:Env,query:string,limit=8):Promise<EvidenceHit[]>{const id=env.MEDICAL_EVIDENCE.idFromName("global"),stub=env.MEDICAL_EVIDENCE.get(id),e=await embed(env,[query]);return stub.search(e[0]||[],limit)}
export async function ingestSource(env:Env,source:LiveSource):Promise<any>{const r=await fetch(source.url,{headers:{"user-agent":"Nexa-AI-Medical-Evidence/1.0"},redirect:"follow"});const raw=await r.text();if(!r.ok)return{id:source.id,changed:false,status:r.status,error:`HTTP ${r.status}`};const text=cleanText(raw),contentHash=await sha256(text),version=contentHash.slice(0,16),stub=env.MEDICAL_EVIDENCE.get(env.MEDICAL_EVIDENCE.idFromName("global")),existing=await stub.listSources(),old=existing.find((x:any)=>x.id===source.id) as any;if(old?.content_hash===contentHash){await stub.upsertSource(source,text,contentHash,version,[],r.status);return{id:source.id,changed:false,version}}const cs=chunks(text),vectors:number[][]=[];for(let i=0;i<cs.length;i+=32){const batch=await embed(env,cs.slice(i,i+32));vectors.push(...batch)}const result=await stub.upsertSource(source,text,contentHash,version,vectors,r.status);return{id:source.id,...result}}
export async function ingestAll(env:Env,sources:LiveSource[]):Promise<any>{const results=[];for(const source of sources){try{results.push(await ingestSource(env,source))}catch(e){results.push({id:source.id,changed:false,error:e instanceof Error?e.message:"ingest_error"})}}return{updatedAt:new Date().toISOString(),results}}
export function explainMedicalAnswer(answer:string){return explainAnswer(answer)}
export async function buildMedicalAudit(env:Env,args:{request:string;query:string;user?:string;hits:EvidenceHit[];answer:string;model?:string;provider?:string;safety?:string[];humanReviewStatus?:MedicalAudit["humanReviewStatus"]}){const explanation=explainAnswer(args.answer),now=new Date().toISOString();return{id:crypto.randomUUID(),createdAt:now,requestHash:await sha256(args.request),queryHash:await sha256(args.query),userHash:args.user?await sha256(args.user):undefined,sourceIds:args.hits.map(h=>h.sourceId),chunkIds:args.hits.map(h=>h.chunkId),sourceVersions:args.hits.map(h=>h.version),retrievalTimestamp:args.hits[0]?.retrievedAt||now,model:args.model||"unknown",provider:args.provider||"unknown",answerHash:await sha256(args.answer),generatedConclusion:explanation.conclusion,uncertainty:explanation.uncertainty,humanReviewStatus:args.humanReviewStatus||"required",safety:args.safety||["live-evidence-linked","citation-level-provenance","stale-sources-excluded","input-and-answer-hashed","hash-chain-record","human-review-required-for-clinical-decisions"]}}
export async function hashAuditInput(value:string):Promise<string>{return sha256(value)}
